### **NumPy For Machine Learning**

In [30]:
import numpy as np
np.version.full_version

'2.3.4'

In [31]:
a = np.array([0,1,2,3,4,5])

a

array([0, 1, 2, 3, 4, 5])

In [32]:
# A one dimensional (.ndim) array of 6 elements (.shape)
print(a.ndim)
print(a.shape)

1
(6,)


We can now transform this array in to a 2D matrix

In [33]:
# Reshaping the array into a two dimensional array of 3 rows and 2 columns (3,2)
aa1 = a.reshape(3,2)
aa1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
print(aa1.ndim)
print(aa1.shape)

2
(3, 2)


In [35]:
# Reshaping the array into a two dimensional array of 2 rows and 3 columns (2,3)

aa2 = a.reshape(2,3)
aa2

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
print(aa2.ndim)
print(aa2.shape)

2
(2, 3)


Preserving the true copy of a array

In [37]:
## Only array "aa1" was altered but the change affected all others 
## The original content of all arrays were overighted
aa1[1][0] = 77
print(aa1)
print(aa2)
print(a)

[[ 0  1]
 [77  3]
 [ 4  5]]
[[ 0  1 77]
 [ 3  4  5]]
[ 0  1 77  3  4  5]


In [38]:
## To maintain the True copy the data the alteration should be done on a Copy (.copy())
ac = a.reshape((3,2)).copy()
ac

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [39]:
# Here, c and a are totally independent copies because it's the copy that was altered
ac[0][0] = -99
print(a, '\n')

print(ac)

[ 0  1 77  3  4  5] 

[[-99   1]
 [ 77   3]
 [  4   5]]


Another big advantage of NumPy arrays is that the operations are propagated
to the individual elements.

In [40]:
print(a, )
a * 2

[ 0  1 77  3  4  5]


array([  0,   2, 154,   6,   8,  10])

In [41]:
print(a**2)

print(a > 4)

[   0    1 5929    9   16   25]
[False False  True False False  True]


#### **Indexing** 


In [42]:
# Using arrays as indices
print(a, '\n')

# Accessing the 2nd, 3rd, and fourth elements of array 'a' with and array of indices 
a[np.array([2,3,4])]

[ 0  1 77  3  4  5] 



array([77,  3,  4])

In [43]:
print(a > 4)

## Accessing all the values greater than 4 in array 'a'
a[a > 4]

[False False  True False False  True]


array([77,  5])

In [44]:
## This can be used to even alter different elements of the dataset all at once
print(aa1)

## Using this to trim all outliers 
aa1[aa1 > 4] = 4
aa1

[[ 0  1]
 [77  3]
 [ 4  5]]


array([[0, 1],
       [4, 3],
       [4, 4]])

In [45]:
## Triming can also be achieved by using the '.clip()' function
print(a)

a.clip(0,4)

[0 1 4 3 4 4]


array([0, 1, 4, 3, 4, 4])

Handling Non-existing values

In [50]:
c = np.array([1, 2, np.nan, 3, 4]) # let's pretend we read this from a txt file
print(c)

np.isnan(c)

[ 1.  2. nan  3.  4.]


array([False, False,  True, False, False])

In [58]:
print(c[~np.isnan(c)])

c[np.isnan(c)] = np.mean(c[~np.isnan(c)])

c

[1.  2.  2.5 3.  4. ]


array([1. , 2. , 2.5, 3. , 4. ])